#pragma once

enum class BlockShape {
    INVISIBLE = -1,
    BLOCK = 0,
    CROSS_TEXTURE = 1,
    TORCH = 2,
    FIRE = 3,
    WATER = 4,
    RED_DUST = 5,
    ROWS = 6,
    DOOR = 7,
    LADDER = 8,
    RAIL = 9,
    STAIRS = 0xA,
    FENCE = 0xB,
    LEVEL = 0xC,
    CACTUS = 0xD,
    BED = 0xE,
    DIODE = 0xF,
    IRON_FENCE = 0x12,
    STEM = 0x13,
    VINE = 0x14,
    FENCE_GATE = 0x15,
    CHEST = 0x16,
    LILYPAD = 0x17,
    BREWING_STAND = 0x19,
    PORTAL_FRAME = 0x1A,
    COCOA = 0x1C,
    TREE = 0x1F,
    WALL = 0x20,
    DOUBLE_PLANT = 0x28,
    FLOWER_POT = 0x2A,
    ANVIL = 0x2B,
    CROSS_TEXTURE_POLY = 0x41,
    DOUBLE_PLANT_POLY = 0x42,
    BLOCK_HALF = 0x43,
    TOP_SNOW = 0x44,
    TRIPWIRE = 0x45,
    TRIPWIRE_HOOK = 0x46,
    CAULDRON = 0x47,
    REPEATOR = 0x48,
    COMPARATOR = 0x49,
    HOPPER = 0x4A,
    SLIME_BLOCK = 0x4B,
    PISTON = 0x4C,
    BEACON = 0x4D,
    CHORUS_PLANT = 0x4E,
    CHORUS_FLOWER = 0x4F,
    DRAGON_EGG = 0x2C,

    END_PORTAL = 0x50,
    END_ROD = 0x51,
    STRUCTURE_VOID = 0x30
};

